#!/bin/sh
HOST='sftp://10.3.16.15'
USER='lftp'
PASSWORD='Dts@2020'

# DISTANT DIRECTORY
REMOTE_DIR='/home/lftp/'

#LOCAL DIRECTORY
LOCAL_DIR='/tmp/lftp/'

# RUNTIME!
echo
echo "Starting download $REMOTE_DIR from $HOST to $LOCAL_DIR"
date

lftp -u "$USER","$PASSWORD" $HOST <<EOF
# the next 3 lines put you in ftpes mode. Uncomment if you are having trouble connecting.
# set ftp:ssl-force true
# set ftp:ssl-protect-data true
# set ssl:verify-certificate no
# transfer starts now...
# set sftp:auto-confirm yes
mirror --use-pget-n=10 $REMOTE_DIR $LOCAL_DIR;
bye
EOF
#exit
#EOF
#echo
#echo "Transfer finished"
#date
#"
